# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itunes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.BigIntegerField()),
                ('collection_name', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_ensored_name', models.CharField(blank=True, max_length=100, null=True)),
                ('collection_explicitness', models.CharField(blank=True, max_length=20, null=True)),
                ('content_advisory_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('feed_url', models.URLField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('collection_view_url', models.URLField(blank=True, null=True)),
                ('artist_name', models.CharField(blank=True, max_length=100, null=True)),
                ('artwork_30', models.URLField(blank=True, null=True)),
                ('artwork_60', models.URLField(blank=True, null=True)),
                ('artwork_100', models.URLField(blank=True, null=True)),
                ('artwork_600', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItunesCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItunesGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='itunes',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.ItunesCountry'),
        ),
        migrations.AddField(
            model_name='itunes',
            name='genre',
            field=models.ManyToManyField(blank=True, to='directory.ItunesGenre'),
        ),
        migrations.AddField(
            model_name='itunes',
            name='primary_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_genre', to='directory.ItunesGenre'),
        ),
    ]
