# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20160902_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itunes',
            name='collection_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
