# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_remove_itunescountry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itunes',
            name='collection_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
