# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20160902_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itunes',
            name='collection_ensored_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
