# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_auto_20160902_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itunes',
            name='collection_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='itunes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='itunes',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='itunescountry',
            name='name',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='itunesgenre',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='itunesgenre',
            name='number',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
